# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  logseq = {
    pname = "logseq";
    version = "a4963dca579f42817135d8473166a03fa7ea2409";
    src = fetchFromGitHub {
      owner = "logseq";
      repo = "logseq";
      rev = "a4963dca579f42817135d8473166a03fa7ea2409";
      fetchSubmodules = false;
      sha256 = "sha256-Ql6AVmLjmyoi9x8qId3PdrfH5zKS3qgFOi/R9dOK6wc=";
    };
    date = "2026-07-17";
  };
}
