# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  logseq = {
    pname = "logseq";
    version = "5ab24c629af07c45f66aa1ff974aa7fb4171fa41";
    src = fetchFromGitHub {
      owner = "logseq";
      repo = "logseq";
      rev = "5ab24c629af07c45f66aa1ff974aa7fb4171fa41";
      fetchSubmodules = false;
      sha256 = "sha256-0K1E/lWkTY0tjoYl2egaDMa2k6ORDCmRzq15UVpxFlE=";
    };
    date = "2026-06-07";
  };
}
