# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  logseq = {
    pname = "logseq";
    version = "466647ef3d6d26dd517cd7440635bf962c810de7";
    src = fetchFromGitHub {
      owner = "logseq";
      repo = "logseq";
      rev = "466647ef3d6d26dd517cd7440635bf962c810de7";
      fetchSubmodules = false;
      sha256 = "sha256-pD+4UplZ0na3a47Kte9lgl6UrO71hjH9mwUiI6HMnOY=";
    };
    date = "2026-05-18";
  };
}
